linux-x86_64-gcc_task:
  container:
    image: ubuntu:latest

  setup_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential git cmake libsdl2-dev

  matrix:
    - build_script:
        - mkdir build && cd build
        - cmake .. -G "Unix Makefiles" -DBUILD_EXAMPLE="ON" -DCMAKE_BUILD_TYPE="Release"
        - make -j4

linux-x86_64-clang_task:
  container:
    image: ubuntu:latest

  setup_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install clang clang-format libc++-dev git cmake libsdl2-dev

  matrix:
    - build_script:
        - mkdir build && cd build
        - cmake .. -G "Unix Makefiles" -DBUILD_EXAMPLE="ON" -DCMAKE_BUILD_TYPE="Release"
        - make -j4