language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake

script:
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles"
  - make -j4
  
