--- 
addons: 
  apt: 
    packages: 
      - cmake
before_install: 
  - "sudo apt-get install libsdl2-dev"
compiler: 
  - gcc
  - clang
dist: bionic
language: cpp
os: linux
script: 
  - "mkdir build && cd build"
  - "cmake .. -G \"Unix Makefiles\" -DBUILD_EXAMPLE=\"ON\" -DCMAKE_BUILD_TYPE=\"Release\""
  - "make -j4"