language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./compilelinux.sh          ; fi
