branches:
  only:
    - master
    - cpu

image:
- Visual Studio 2017

environment:
  matrix:
    - MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
    - MSYS2_ARCH: i686
      MSYSTEM: MINGW32


build_script:
  - SET PATH=%PATH%;c:\msys64\bin;c:\msys64\usr\bin
  - mkdir build && cd build
  - cmake .. -G "MSYS Makefiles"
  - mingw32-make -j4
